### ISSUE TITLE
Change the log store directory in pod-simulator

### ISSUE THREAD

**Issue by MrSupiri** [MrSupiri/rancher-logging-explorer#15]
> var logs is a system directory, in our context this is application data.  It should go in `/etc/pod-simulator` or be passed in as an argument.  I would opt for the argument approach, it gives us much more flexibility in the future.

_Originally posted by @paynejacob in https://github.com/MrSupiri/rancher-logging-explorer/pull/11#r668042788_

**Comment by paynejacob** [comment]
e.g. /bin/pod-simulator /foo/bar/dat.log

**Comment by paynejacob** [comment]
suggested layout

/usr/local/bin/pod-simulator for the compiled binary

/data.log for the log messages from the configmap

change the container command to pod-simulator /data.log

**Comment by paynejacob** [comment]
version: `255eabe`

# Simulator supports log file as argument

## Steps Taken
1. clone repo
2. `docker build -t sim:dev -f pod-simulator/Dockerfile ./pod-simulator`
3. `echo "foo\nbar\nbaz" > mock-logs`
3. `docker run -v <abs path>/mock-logs:/data/mock-logs:ro sim:dev -log-dir /data/mock-logs` 

## Expected Result
- container starts with no errors
- each log message in the log file is logged in a loop

## Actual Result
- no logs are seen
- the flag name `log-dir` is misleading and should be renamed to `log_file`

**Comment by MrSupiri** [comment]
I am not sure what `:ro` does but it works after removing it.

![image](https://user-images.githubusercontent.com/29277992/127444219-cc00127e-6cb7-457b-b3ea-868b8a1cc8dd.png)

**Comment by paynejacob** [comment]
Ro means read only.  It failed because we open the file with write permissions, this is unnecessary but not worth fixing for now.

**Comment by paynejacob** [comment]
Version: `a6b2fa1`

works as expected
